### ISSUE TITLE
Max volume and volume smoothing duration

### ISSUE THREAD

**Issue by cjh9** [escottalexander/simpleTones.js#1]
Great library! Would there be a possibility to change the max volume and the smoothing? I thing it increases and decreases the volume (fading) to slowly for my application.

**Comment by escottalexander** [comment]
@cjh9 This would be a great feature. Thanks for thinking of it. Any interest in digging into the code to find out how you could do that?

**Comment by peilingjiang** [comment]
Is it possible to support max/average volume first, if the smoothing takes more time? It would be great if `playTone` takes a 4th param to control the volume of the tone.
