### ISSUE TITLE
Demo website not working.

### ISSUE THREAD

**Issue by lilplayer6k** [escottalexander/simpleTones.js#17]
Hello there @escottalexander ! i do not know if you know or not but it seems to be that your demo website does not work. it seems to redirect me to another website and says page not found. if you can, please do fix this issue, thanks! <3
![image](https://user-images.githubusercontent.com/78946868/111661033-e8df6f00-87cb-11eb-97f2-ef47babcf22c.png)

**Comment by jjws600** [comment]
https://escottalexander.github.io/simpleTones.js/

**Comment by escottalexander** [comment]
Thanks guys! Link updated in readme.
