### ISSUE TITLE
Question: #HowTo download a generated sound?

### ISSUE THREAD

**Issue by tst32** [escottalexander/simpleTones.js#19]
How to download a generated sound?
to save it to fs or just upload somewhere?

**Comment by zikmu3** [comment]
Hi! @tst32 
I am also interested in that question. Did anyone answered you?
Thank you

Alexandre

**Comment by escottalexander** [comment]
This library does not provide a way to download the sound as an audio file. That's a neat idea though. Feel free to submit a PR if you want to add that feature.
