### ISSUE TITLE
Play F2 not possible as a sine wave

### ISSUE THREAD

**Issue by cjh9** [escottalexander/simpleTones.js#2]
Try to play this.. `playTone("F2",'sine',3)`

I get no sound. Would there be possible to get a piano sound that you can play on all notes like here?

http://www.apronus.com/music/flashpiano.htm

**Comment by escottalexander** [comment]
@cjh9 I have attempted to create the same problem but it works for me. What browser are you using? Any other ideas about why this wouldn't be working for you? Thanks.
