### ISSUE TITLE
Not working on iOS Safari

### ISSUE THREAD

**Issue by cjh9** [escottalexander/simpleTones.js#3]
This could maybe be a hint https://groups.google.com/forum/#!topic/tonejs/_Uaavm8wU-4

**Comment by escottalexander** [comment]
@cjh9 Can you give me more data on what device you are using and how you tested this? It seems to be working on my iPhone 6s with the latest version of Safari.

**Comment by DaltonWebDev** [comment]
Doesn’t work for iOS safari for me also. iOS 15

**Comment by DaltonWebDev** [comment]
I’m back because I know why it doesn’t work. You need to run oscillator.start(); inside a event listener such as click. Due to browser security policy

**Comment by escottalexander** [comment]
@DaltonWebDev Nice info. Thanks! Do you want to try your hand at submitting a Pull Request with that change?
